title: KyoJun Choo
url: "https://chubeloop.github.io"
baseurl: ""

markdown: kramdown

footer: no

sass:
  style: compressed
  sass_dir: _sass

nav:
 - name: "CV"
   link: "/cv/"
 - name: "NLP Lab"
   link: "https://sites.google.com/view/ssu-nlp/home"
