title: KyoJun Choo
url: "https://chubeloop.github.io"
baseurl: ""

author: KyoJun Choo
description: "KyoJun Choo - NLP and Large Language Model researcher at Soongsil University."

markdown: kramdown

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "CV"
    link: "/cv/"
  - name: "NLP LAB"
    link: "https://sites.google.com/view/ssu-nlp/home"
  - name: "Contact"
    link: "/contact/"

remote_theme: ankitsultana/researcher@gem
plugins:
  - jekyll-remote-theme
